### ISSUE TITLE
Support Equality between identical encoders

### ISSUE THREAD

**Issue by oxinabox** [JuliaML/MLLabelUtils.jl#11]
It would be nice if Equality was supported for encoders.

Eg right now:

```julia
using MLLabelUtils

enc1 = labelenc(split("a b c a"))
enc2 = labelenc(split("a b c a"))

​
@show enc1==enc2
@show enc1.invlabel == enc2.invlabel
@show enc1.label == enc2.label
```

output:
```julia
enc1 == enc2 = false
enc1.invlabel == enc2.invlabel = true
enc1.label == enc2.label = true
````

For native encoders equality on either of the fields implies equality of the whole.

**Comment by Evizero** [comment]
Good point. I agree. I actually thought I did this already but the realized I was thinking of MLDataPattern, e.g. https://github.com/JuliaML/MLDataPattern.jl/blob/master/src/folds.jl#L143-L151

**Comment by Evizero** [comment]
fixed on master

**Comment by Evizero** [comment]
also backported to 0.5

**Comment by Evizero** [comment]
0.6: https://github.com/JuliaLang/METADATA.jl/pull/9543
0.5: https://github.com/JuliaLang/METADATA.jl/pull/9542
