### ISSUE TITLE
NativeLabels should probably not be based around Int64

### ISSUE THREAD

**Issue by oxinabox** [JuliaML/MLLabelUtils.jl#14]
Currently, `NativeLabels` will always work in the machine's `Int`.
Which will be `Int64`, on most systems being used for ML.

I suggest that `Int32` everywhere would be better.
Given that it is intended for encoding classes,
having more than ` typemax(Int32)==2_147_483_647` classes,
seems like a not reasonably scenario.
Even in  NLP when learning word-sense vectors, one is still looking at millions of classes -- at most.

Having billions of training case, on the other hand, seems more reasonable.
And in that case, storing them as `Int32` can halve your memory use.

I guess the downside is that if the user mixes them with integer literals,
type promotion will occur, which has a (single operation) computational overhead, and negates the storage benefit.

An argument could be made for using `UInt32`, but I think that would end-up too fiddly.
An argument also could be made for the user to provide the type, with it defaulting to `Int`.
That sounds reasonable.

**Comment by Evizero** [comment]
Are you talking about the inverse index mapping `invlabel` ?

**Comment by oxinabox** [comment]
I was primarily thinking about the result of calling `label2ind`.
If I call `label2ind.(data)`, then I get a `Vector{Int64}`.
I would rather that `label2ind.(data)`, returned a `Vector{Int32}`.
Thus saving me substantial memory.

I think that, yes, as a consequence of this it would change the type of `invlabel`

**Comment by Evizero** [comment]
Hmm, I see. `label2ind` is the common denominator for all the labelencodings, so as the code is now we would need to settle for one common type `Int32` or `Int64`. I acknowledge that `Int32` should be enough though.

As a side note. Why are you using `label2ind` directly? Its more of a back-end function. If you want to convert some label vector into numbers you may be better off with

```julia
julia> convertlabel(LabelEnc.Indices{Int32}, [:a,:b,:c,:b,:a])
5-element Array{Int32,1}:
 1
 2
 3
 2
 1
```

**Comment by oxinabox** [comment]
I never knew about `convertlabel`
I was like: _"I have a label, I want an index. What would the function for converting a label into an Index be? What about `label2ind`? Yes that seems to work."_

My usage of it is at: https://github.com/oxinabox/ColoringNames.jl/blob/50fe81ec013d340cce37c9b1b4b183e7d1f31e31/src/input.jl#L50-L58
