### ISSUE TITLE
Labels for incomplete dataset

### ISSUE THREAD

**Issue by pevnak** [JuliaML/MLLabelUtils.jl#15]
Hello,

Imagine that in my problem I have two classes `[:one,:two]`, which are very imbalanced.  If my data are huge, it can happen that I will load a data only with class `:two`. How can I construct the correct label encoding in this case? 
For example if I want OneOfK encoding for the dataset with samples from only `:two` class, the output should be
```
[0 1,
 0 1,
 0 1,
 0 1,
 ...
 0 1].
```

I was not able to figure out, if such feature is supported.
Thanks for the answer.
Tomas

**Comment by Evizero** [comment]
```julia
julia> y = [:two, :two, :two, :two]
4-element Array{Symbol,1}:
 :two
 :two
 :two
 :two

julia> labels = [:one, :two]
2-element Array{Symbol,1}:
 :one
 :two

julia> convertlabel(LabelEnc.OneOfK{Int}, y, labels) 
2×4 Array{Int64,2}:
 0  0  0  0
 1  1  1  1
```

**Comment by pevnak** [comment]
This is exactly what I was thinking about. Thank you very much for this.
Best wishes,
Tomas
